### ISSUE TITLE
Host Globals aren't working

### ISSUE THREAD

**Issue by cristian-5** [swiftwasm/WasmKit#131]
### Version 0.0.8
I tried to make a global so I can access it from the module but it appears the initializer of `GlobalInstance` is inaccessible. It might be because it's not marked as public and since it has a `internal(set)` member it's deduced to be internal. On a side-note, for this I needed to import both `WasmParser` and `WasmTypes` which I think it's a bit excessive.

```swift
let runtime = Runtime(hostModules: [ "env": HostModule(globals: [
    "myvalue": GlobalInstance(
        globalType: GlobalType(mutability: .constant, valueType: .f32),
        initialValue: Value.fromFloat32(5.5)
    )
]) ])
```
<img width="889" alt="Screenshot 2024-10-01 at 10 56 37 AM" src="https://github.com/user-attachments/assets/422f0e5c-1cd9-4d13-b434-bde5ca552afb">

## EDIT 1 - Circular Logic - version based on: 4aff9cc5d12649da1b92c72f125233509fd1feff

Everything is completely different in the actual code, in fact, it's still _impossible_ to make a global because **circular logic**: `Global` needs to be initialized with `Store` which you can only get by first making a `Runtime` which asks for your `HostModule`s in which you need to put your `Global`s. **In other words, it's an infinite loop of dependecies.**

> Please help, I just need to import a global variable in my webassembly module 😭

**Comment by kateinoigakukun** [comment]
I'm working on API overhaul towards the next release. I think https://github.com/swiftwasm/WasmKit/pull/132 addressed this issue. Could you try with the latest main?

**Comment by cristian-5** [comment]
It works perfectly now, you should probably make a tag 😄
