### ISSUE TITLE
Import object

### ISSUE THREAD

**Issue by Jomy10** [swiftwasm/WasmKit#60]
I'm skimming through the project trying to figure out how to use the library. One thing I have not found how to do, which is the import object.

I have the following:

```swift
let modInstance = try runtime.instantiate(module: module, externalValues: [
    ExternalValue.function(/*What do I put here?*/)
])
```

What I want to accomplish is calling a Swift function from wasm.

Any help on this?

Thank you in advance,
Jomy

**Comment by kateinoigakukun** [comment]
Several public APIs have been changed since https://github.com/swiftwasm/WasmKit/pull/62 The latest API document describes how to inject function from host side https://swiftpackageindex.com/swiftwasm/WasmKit/main/documentation/wasmkit
