### ISSUE TITLE
Make WASI deterministic

### ISSUE THREAD

**Issue by kabiroberai** [swiftwasm/WasmKit#84]
At the moment it seems like there are two sources of nondeterminism in WASI:

1. The random number generator, which is hardcoded to `swift_stdlib_random`
2. The clocks, hardcoded to the real system clocks

What if we allowed these to be overridden by user-provided `Swift.RandomNumberGenerator` and `Swift.Clock` types respectively? We could default to `SystemRandomNumberGenerator` and `ContinuousClock` + `SuspendingClock`.

To my understanding, enabling these to be overridden would allow for fully deterministic execution of WASI binaries while also serving as Dependency Injection points for solid testability.

**Comment by kateinoigakukun** [comment]
Thanks! I added `WallClock`, `MonotonicClock`, and `RandomBufferGenerator` protocols because stdlib's protocol APIs don't expose enough ability to implement WASI.

**Comment by kabiroberai** [comment]
Looks great, ty! Unsure if clocks and RNG were the only sources of nondeterminism but if so feel free to close this issue!

**Comment by kateinoigakukun** [comment]
We still have nondeterminism for NaN payload bit pattern after fp operations, but wouldn't be a problem for most cases

**Comment by kabiroberai** [comment]
Yeah, nondeterminism in NaN bit patterns is mentioned as an exception in the [design spec](https://github.com/WebAssembly/design/blob/08e06cccaf9fe14558e1f3deec81b3d14175cd4b/Nondeterminism.md) so I think that's fair game.

**Comment by kabiroberai** [comment]
> stdlib's protocol APIs don't expose enough ability to implement WASI

btw any `_Concurrency.Clock` that uses the basic `_Concurrency.Duration` should expose enough API surface (via `Duration.components`) but I agree that using our own protocol makes sense since `Clock` has availability restrictions. Also agree with the custom `RandomBufferGenerator` as an optimization; the default conformance definitely helps.

**Comment by kateinoigakukun** [comment]
> btw any _Concurrency.Clock that uses the basic _Concurrency.Duration should expose enough API surface (via Duration.components)

The problem here is no `Instant.zero` definition. Without that, we cannot get a duration from zero (UNIX epoch) to now 😢
